- name: Update apt-get
  apt: update_cache=yes

- name: Install binutils-avr
  apt: name=binutils-avr state=present

- name: Install libc6-dev
  apt: name=libc6-dev state=present

- name: Install avr-libc
  apt: name=avr-libc state=present

- name: Install gcc-avr
  apt: name=gcc-avr state=present

- name: Install clang
  apt: name=clang state=present

- name: Install avrdude
  apt: name=avrdude state=present

- name: Install make
  apt: name=make state=present

- name: Install libcurl4-gnutls-dev
  apt: name=libcurl4-gnutls-dev state=present

- name: Install git
  apt: name=git state=present

- name: Install astyle
  apt: name=astyle state=present

- include: clib.yml
- include: quartz.yml
